# Generated by Django 5.2.9 on 2025-12-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0002_remove_pedido_pizza_remove_pedido_preco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='sabores',
            field=models.TextField(blank=True, help_text='JSON com sabores múltiplos', null=True),
        ),
    ]
