# Generated by Django 5.2.9 on 2025-12-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0003_itempedido_sabores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='preco',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='borda_chocolate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='catupiry_borda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='catupiry_cima',
            field=models.CharField(choices=[('nao', 'Não'), ('inteira', 'Inteira'), ('metade', 'Metade')], default='nao', max_length=10),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='tamanho',
            field=models.CharField(choices=[('P', 'Pequena'), ('M', 'Média'), ('G', 'Grande')], default='G', max_length=1),
        ),
        migrations.AddField(
            model_name='pizza',
            name='especial',
            field=models.BooleanField(default=False, help_text='Atum, Carne de Sol ou 4 Queijos'),
        ),
    ]
