# Generated by Django 5.2.4 on 2025-12-22 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0004_remove_pizza_preco_itempedido_borda_chocolate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da localidade', max_length=100, unique=True)),
                ('taxa', models.DecimalField(decimal_places=2, default=0, help_text='Valor da taxa de entrega', max_digits=6)),
                ('ativo', models.BooleanField(default=True, help_text='Se a entrega está disponível para este local')),
            ],
            options={
                'verbose_name': 'Taxa de Entrega',
                'verbose_name_plural': 'Taxas de Entrega',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total sem taxa de entrega', max_digits=8),
        ),
        migrations.AddField(
            model_name='pedido',
            name='taxa_entrega',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor da taxa de entrega', max_digits=6),
        ),
        migrations.AddField(
            model_name='pedido',
            name='local_entrega',
            field=models.ForeignKey(blank=True, help_text='Local de entrega (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pizzaria.taxaentrega'),
        ),
    ]
