# Generated by Django 5.2.9 on 2026-08-30 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0008_pizza_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('disponivel', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bebida',
                'verbose_name_plural': 'Bebidas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='itempedido',
            name='item_tipo',
            field=models.CharField(choices=[('pizza', 'Pizza'), ('bebida', 'Bebida')], default='pizza', max_length=10),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='pizzaria.pizza'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='bebida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='pizzaria.bebida'),
        ),
    ]
