# Generated by Django 5.2.9 on 2026-08-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0009_bebida_itempedido_item_tipo_alter_itempedido_pizza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='bebidas/'),
        ),
    ]
