# Generated by Django 5.2.9 on 2026-09-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0010_bebida_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='troco',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Em andamento', 'Em andamento'), ('Em preparo', 'Em preparo'), ('Pronto', 'Pronto'), ('Entregue', 'Entregue')], default='Novo', max_length=20),
        ),
    ]
