# Generated by Django 5.2.9 on 2026-09-04 03:51

from django.db import migrations, models


def converter_entregue_para_pago(apps, schema_editor):
    Pedido = apps.get_model('pizzaria', 'Pedido')
    Pedido.objects.filter(status='Entregue').update(status='Pago')


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0011_pedido_forma_pagamento_pedido_troco_and_more'),
    ]

    operations = [
        migrations.RunPython(converter_entregue_para_pago, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Em andamento', 'Em andamento'), ('Em preparo', 'Em preparo'), ('Pronto', 'Pronto'), ('Pago', 'Pago')], default='Novo', max_length=20),
        ),
    ]
