# Generated by Django 5.2.9 on 2026-09-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0012_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Em andamento', 'Em andamento'), ('Em preparo', 'Em preparo'), ('Pronto', 'Pronto'), ('Entregue', 'Entregue'), ('Pago', 'Pago')], default='Novo', max_length=20),
        ),
    ]
