# Generated by Django 5.2.9 on 2026-09-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0013_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fechado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='reaberto_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
