# Generated by Django 5.2.9 on 2026-09-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0014_pedido_fechado_em_pedido_reaberto_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
