# Generated by Django 5.2.9 on 2026-09-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0014_pedido_fechado_em_pedido_reaberto_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
